# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: NowSecure Platform Integration
      uses: blawrencens/nowsecure-actions-integration@0.2.0
      with:
        # Please provide the path for the app to be uploaded
        app-path: $GITHUB_WORKSPACE/anydo39.apk
        # Please provide the API Key for NowSecure Platform
        api-key: ${{ secrets.PLATFORM_API_KEY }}
        # Please provide the Group Id of the application being integrated
        group-id: "a27a22b7-d9a0-4b1e-81b8-0f847029e0f5"
